INSERT INTO category (name) VALUES ('Alimentos');
INSERT INTO category (name) VALUES ('Eletrodomésticos');
INSERT INTO category (name) VALUES ('Móveis');
INSERT INTO product (name, id_category) VALUES ('Arroz', 1);
INSERT INTO product (name, id_category) VALUES ('Feijão', 1);
INSERT INTO product (name, id_category) VALUES ('Aspirador de pó', 2);
INSERT INTO product (name, id_category) VALUES ('Batedeira', 2);
INSERT INTO product (name, id_category) VALUES ('Liquidificador', 2);
INSERT INTO product (name, id_category) VALUES ('Sofá', 3);
INSERT INTO product (name, id_category) VALUES ('Mesa', 3);
INSERT INTO product (name, id_category) VALUES ('Estante', 3);